name: Build Web

on: 
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: subosito/flutter-action@v2
              with:
                channel: stable
                flutter-version: 3.22.2
            - run: flutter pub get

            - run: flutter test 

            - run: flutter analyze 

            - run: flutter build web --release lib/main.dart

            - uses: bluefireteam/flutter-gh-pages@v7
              with:
                baseHref: /new_app/
                customArgs: --target="lib/main.dart"
        